language: ruby
rvm:
- 2.3.1
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: 1LCMYp1Hod/qLBBspUFdJbVGU46K4RMbJJ08fb0DNnruBv0nU5kVG8s2XvKKs0YsX2xiCx35CEcaYthRv/pHrtJtsO/gpSCIWUywRY6MZchhyc5y4tF218+ci5Q1JD5hBMRoe5NO1mCbYXTbZ8XoPXWEMRSlV/r3fkyVYwoFW8ohmPbbYcopXYSfOQ9Qn87W7Suee+kwnVJtyNA/LrGNNHOyTzynSN/45UpbzQMsdnNl0zEHQgSPgpsXjv15acqpMbMEXiFNq00tYR94rQJYpvrn/vTE/UyYhlLQgrf0IxIlDOn4jTw1HxEy5mVF2G4CeX6HPi3rCoTHAWfE30dgl5QJWLEZobBFdZRoYw+O1i4NjplFbN44J09Xq10OJKGk6MbMJfnKdVTJF8tFAwWs3wVvwcD3g7gbAqc6qlcy6yWk169+Mg6No9SzoUHCU35pM9kVr/dlPA/quZPjxXTd5lt48t18fQ0j2VrDRtz2c2MsLhdsqDeJe8OGPqktBSZl/J77gkgT8oEUP5JUHPcxEjKha26kWQW3RaYNrzTF5GXeq2m2hAL6y9LadX7oMnAApXvHXPunA57ofFNCY7jrVog3KgxUAAgBYfecThQsWlX6pmc4KeEWswvRZ8kCXbEOv3pojaqIkb8E8F0SXFs9317JWhnrECtmmsGDqgdhmJg=
  app: sheltered-lake-27168
  on:
    repo: sambo1111/ratebeer
env:
  matrix:
    secure: OlQpjmEX1s6UMC1WdLHwZBYgwk1jNIk5K7WC/d7b1N9gTwhlvmV88YJfyeqDI1CBvUMhPp1ZuFrX9DPQIYAnjtC+4J65QiRUoK+MLpgzyCY/s+rO9Cnod6e3TqsN0qQpIlC+i40pOlydCFOrfUXZnx85bOrxU/XY5D+Ls+p8DeDoQFPowHuJD83mI9/KcT2jJClBbgqpnnV6q3kEl4NKycuC4iQRB6a4oIGzZo6BF1tg8Qi0x732gdSfM+DUkeV87/kmTCKP0toAU33ab0OPn/X0lOTRT3UmnYSHEODXKvmmujg6Pq6TDPMwxhBaGo9weXHVw66ySbh7ESxWLcs3/K2JxMO4LNhTR2GbZldYe1UdCpJZ0PZG8J39RausrR8Cg8gZwnOcIBFUNC1Q1jWmaL/EmQnZCOdZm8QuhycnTRz14RRjafK6Lu9NxNoCYwHFzlkGxZWBbykd4sUOX9L8Hb1JTpfYcMqmlpB520pDU6E+LjNrU655iEoytgNfIlJAubkr3NY4VI7AE0O6M8gt+giByfngu5hw22MxFGP+DO/s+uTSi6ri7fCGx0Rrh1sLuURlIZkNPEedzCP1LuGA38MCdW4MSNyF477cj8LG21DVnG3DmGqEVUbPSTUH0Z2z1g0/W4nsg7FfCnP5tJkEGNhgoHXehpfuMFgWf0I3vvk=
