# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b09ff4509f2f78c15ab814ac773c74e159a161b3e92a77decea785a5a1ba68cbd9213f69a53ac2504d0ba10e7790d2118962e63be4b3502bdb4dbdb8d02f182a

test:
  secret_key_base: 95bfcdcc8ee00d5e942634e47df5c1e5eace5543e05aa5bb0575e47bf43902e651288d98ddafce9a6b64e7251ac932fa9ef20c97a15fdb615d3168e9a25a5def

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
